### ISSUE TITLE
Help with Cell Type Label

### ISSUE THREAD

**Issue by B-Y03** [PYangLab/Matilda#5]

**Comment by liuchunlei0430** [comment]
The TEA-seq data is obtained from the following paper: https://elifesciences.org/articles/63632/figures#files. 

You can access the cell type labels by clicking on 'Figures and Data,' navigating to Figure 4, and downloading the file 'elife-63632-fig4-data2-v2.zip' under Figure 4—source data 2 "Fractions of cells assigned to each type by flow cytometry and scATAC-seq". 

Hope this can help.

**Comment by B-Y03** [comment]
Thanks for your response! it's really helpful!

**Comment by Hw-31016** [comment]
May I know which batch of GSE158013 you used to match those cell type labels, I didn't find the corresponding barcode in GSE158013 w1-w6 batch which contains adt,rna,atac. I would appreciate if you could answer me.
